apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
#  googleCloudBuild:
#    projectId: 	ticketing-dev-322612
  artifacts:
  - image: alexostapiuk/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yml
